"use client";

import { useEffect, useRef } from "react";
import * as RadixDialog from "@radix-ui/react-dialog";
import { Info, MessageCircleQuestion, RotateCcw, X } from "lucide-react";
import { greetingFor, PAGE_GUIDES } from "@/lib/ai/context";
import { useJourney } from "@/lib/journey/store";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { useAssistant } from "./AssistantProvider";
import { AssistantAvatar, ChatMessage, RichText, TypingIndicator } from "./ChatMessage";
import { ChatInput } from "./ChatInput";
import { SuggestedQuestions } from "./SuggestedQuestions";

export const ASSISTANT_DISCLAIMER =
  "Loan Assistant provides general guidance. Final eligibility, terms and approval are subject to the lender's assessment.";

/**
 * The contextual assistant panel. Non-modal on desktop so the customer can
 * keep filling the form beside it; full-screen on mobile.
 */
export function LoanAssistant() {
  const { open, close, pending, mode, page, context, send, retryLast } = useAssistant();
  const { state, actions } = useJourney();
  const scrollRef = useRef<HTMLDivElement>(null);
  const guide = PAGE_GUIDES[page];
  const lastIsUnavailable = state.chat[state.chat.length - 1]?.mode === "unavailable";

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [state.chat.length, pending, open]);

  // Suggestions not yet asked in this conversation.
  const asked = new Set(state.chat.filter((m) => m.role === "user").map((m) => m.content));
  const suggestions = guide.suggestions.filter((q) => !asked.has(q));

  return (
    <RadixDialog.Root open={open} onOpenChange={(o) => !o && close()} modal={false}>
      <RadixDialog.Portal>
        <RadixDialog.Content
          onInteractOutside={(e) => e.preventDefault()}
          onOpenAutoFocus={(e) => {
            e.preventDefault();
            document.getElementById("assistant-input")?.focus();
          }}
          className="fixed inset-0 z-[60] flex flex-col bg-white shadow-raised data-[state=open]:animate-fade-up sm:inset-auto sm:top-3 sm:right-3 sm:bottom-3 sm:w-[420px] sm:rounded-3xl sm:border sm:border-slate-200"
        >
          {/* Header */}
          <div className="flex items-center gap-3 border-b border-slate-100 px-4 py-3.5 sm:px-5">
            <AssistantAvatar className="size-9" />
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-2">
                <RadixDialog.Title className="text-[15px] font-semibold text-slate-900">Loan Assistant</RadixDialog.Title>
                {mode && (
                  <Badge tone={mode === "live" ? "brand" : "neutral"} title={mode === "live" ? "Answers generated by AI using your journey context" : "No AI key configured — answers come from saved guidance"}>
                    {mode === "live" ? "AI" : "Demo mode"}
                  </Badge>
                )}
              </div>
              <RadixDialog.Description className="truncate text-[12.5px] text-slate-500">Helping with: {guide.title}</RadixDialog.Description>
            </div>
            {state.chat.length > 0 && (
              <button onClick={actions.clearChat} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-800" aria-label="Start a new conversation" title="New conversation">
                <RotateCcw className="size-4" />
              </button>
            )}
            <RadixDialog.Close className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-800" aria-label="Close Loan Assistant">
              <X className="size-5" />
            </RadixDialog.Close>
          </div>

          {/* Conversation */}
          <div ref={scrollRef} className="flex-1 space-y-4 overflow-y-auto px-4 py-5 sm:px-5" aria-live="polite">
            <div className="flex gap-2.5">
              <AssistantAvatar className="mt-0.5" />
              <div className="max-w-[88%] rounded-2xl rounded-tl-md bg-slate-100 px-4 py-3 text-[14.5px] leading-relaxed text-slate-800">
                <RichText content={greetingFor(context)} />
              </div>
            </div>
            {state.chat.map((m, i) => (
              <ChatMessage key={m.id} message={m} onRetry={i === state.chat.length - 1 && !pending ? retryLast : undefined} />
            ))}
            {pending && <TypingIndicator />}
            {!pending && !lastIsUnavailable && suggestions.length > 0 && (
              <div className="pt-1">
                <p className="mb-2 flex items-center gap-1.5 text-[12px] font-medium tracking-wide text-slate-500 uppercase">
                  <MessageCircleQuestion className="size-3.5" aria-hidden /> {state.chat.length ? "You could also ask" : "Common questions here"}
                </p>
                <SuggestedQuestions questions={suggestions.slice(0, state.chat.length ? 3 : 4)} onPick={send} disabled={pending} />
              </div>
            )}
          </div>

          {/* Input + disclaimer */}
          <div className={cn("border-t border-slate-100 px-4 pt-3 pb-[max(12px,env(safe-area-inset-bottom))] sm:px-5")}>
            <ChatInput onSend={send} disabled={pending} />
            <p className="mt-2.5 flex items-start gap-1.5 text-[11.5px] leading-snug text-slate-500">
              <Info className="mt-px size-3 shrink-0" aria-hidden />
              {ASSISTANT_DISCLAIMER}
            </p>
          </div>
        </RadixDialog.Content>
      </RadixDialog.Portal>
    </RadixDialog.Root>
  );
}
